PRECONVERT – Flex_extract: Calculation of etadot
PRECONVERT Program
370 statements
Source File
Uses
PHTOGR
GRTOPH
FTRAFO
RWGRIB2
GRIB_API
Prepare input data for FLEXPART, esp. vertical velocity as etadot or etadot * dp/deta
author: L. Haimberger date: 03/2010 version: V4.0
Program PRECONVERT
Prepares input data for POP model meteorological preprocessor
Calculation of etapoint on a regular grid and writing U,V,ETAPOINT,T,PS,Q,SD,MSL,TCC,10U, 10V, 2T,2D,LSP,CP,SSHF,SSR, EWSS,NSSS to an output file (input and output in GRIB 1 or 2 format).
etapoint is defined as the total time derivative of ECMWF vertical coordinate eta multiplied by the derivative of pressure with respect to eta:
Version history and authors:
04/1994: Leopold Haimberger, Gerhard Wotawa
2003-05-11: Alexander Beck
12/2006: L. Haimberger V2.0, handle arbitrary regular grids and T799 resolution data
03/2010: L. Haimberger V4.0, handle GRIB edition 2 fields and T1279 resolution data
04-06/2019: Petra Seibert, beautify code and add FORD documentation
#
Input required:
 UNIT  FILE      PARAMETER(S)    DATA REPRESENTATION
 11    fort.11   T,U,V           regular lambda phi grid
 12    fort.12   D               regular lambda phi grid
 13    fort.13   LNSP            spherical harmonics
 14    fort.14   SD,MSL,TCC,10U,
                 10V,2T,2D       regular lambda phi grid
 16    fort.16   LSP,CP,SSHF,
                 SSR,EWSS,NSSS   regular lambda phi grid
 17    fort.17   Q               regular lambda phi grid
Output produced:
UNIT  FILE      PARAMETER(S)      DATA REPRESENTATION
15    fort.15   `U,V,ETA,T,PS,
                `Q,SD,MSL,TCC,`
                `10U,10V,2T,2D,`  regular lambda phi grid
                `LSP,CP,SSHF,`
                `SSR,EWSS,NSSS`
ALLOCATE VARIABLES
Initialisieren Legendretransformation auf das LaT/LON Gitter
Initialisation of fields for FFT and Legendre transformation to Gaussian grid and back to phase space Transformieren des Windes auf das Gaussgitter
Transformieren der horizontalen Divergenz auf das Gaussgitter
Berechnung des Gradienten des Logarithmus des Bodendrucks auf dem Gaussgitter
Berechnung der Vertikalgeschwindigkeit auf dem Gaussgitter
Berechnung von Omega auf dem Gaussgitter
READING OF SURFACE PRESSURE
READING OF U,V
READING OF LNSP on grid
READING OF DIVERGENCE
Initialisieren Legendretransformation auf das LaT/LON Gitter Without Gaussian grid calculation Legendre Polynomials are calculated only for one latitude to save space
CREATE FILE VERTICAL.EC NEEDED BY POP MODEL
READING OF T
READING OF SPECIFIC HUMIDITY
WRITE MODEL LEVEL DATA TO fort.15
 Calculation of etadot in CONTGL needed scaled winds (ucosphi,vcosphi)
 Now we are transforming back to the usual winds.
Calls
Contents
Variables
LNPS Z T UV UV2 QA OM OMR DIV ETA ETAR DPSDL DPSDM PS DPSDT SURF FLUX OROLSM WSAVE H SINL COSL WSAVE2 BREITE GBREITE AK BK pv X1 X2 RMS MW SIG LAM CUA CVA P PP P2 XMN HILFUV LNPMN LNPMN2 LNPMN3 WEIGHT UGVG DG ETAG GWSAVE PSG HILF MLAT MPSURF MPFLUX MPORO MPAR GIFAX PI COSB DAK DBK P00 URLAR8 JMIN1 LLLAR8 MAXBMIN1 PIR8 DCOSB I J K L IERR M LTEST MK NGI NGJ MFLUX MSURF MORO LUNIT LUNIT2 MAXL MAXB MLEVEL LEVOUT LEVMIN LEVMAX MOMEGA MOMEGADIFF MGAUSS MSMOOTH MNAUF META METADIFF MDPDETA METAPAR RLO0 RLO1 RLA0 RLA1 MLEVELIST MAUF MANF IFAX IGRIB iret ogrib FILENAME
Variables
Type Attributes Name Initial
real, ALLOCATABLE, DIMENSION (:,:) :: LNPS
real, ALLOCATABLE, DIMENSION (:,:) :: Z
real, ALLOCATABLE, DIMENSION (:,:,:) :: T
real, ALLOCATABLE, DIMENSION (:,:,:) :: UV
real, ALLOCATABLE, DIMENSION (:,:,:) :: UV2
real, ALLOCATABLE, DIMENSION (:,:,:) :: QA
real, ALLOCATABLE, DIMENSION (:,:,:) :: OM
real, ALLOCATABLE, DIMENSION (:,:,:) :: OMR
real, ALLOCATABLE, DIMENSION (:,:,:) :: DIV
real, ALLOCATABLE, DIMENSION (:,:,:) :: ETA
real, ALLOCATABLE, DIMENSION (:,:,:) :: ETAR
real, ALLOCATABLE, DIMENSION (:,:) :: DPSDL
real, ALLOCATABLE, DIMENSION (:,:) :: DPSDM
real, ALLOCATABLE, DIMENSION (:,:,:) :: PS
real, ALLOCATABLE, DIMENSION (:,:,:) :: DPSDT
real, ALLOCATABLE, DIMENSION (:,:,:) :: SURF
real, ALLOCATABLE, DIMENSION (:,:,:) :: FLUX
real, ALLOCATABLE, DIMENSION (:,:,:) :: OROLSM
real, ALLOCATABLE, DIMENSION (:) :: WSAVE
real, ALLOCATABLE, DIMENSION (:) :: H
real, ALLOCATABLE, DIMENSION (:) :: SINL
real, ALLOCATABLE, DIMENSION (:) :: COSL
real, ALLOCATABLE, DIMENSION (:) :: WSAVE2
real, ALLOCATABLE, DIMENSION (:) :: BREITE
real, ALLOCATABLE, DIMENSION (:) :: GBREITE
real, ALLOCATABLE, DIMENSION (:) :: AK
real, ALLOCATABLE, DIMENSION (:) :: BK
real, ALLOCATABLE, DIMENSION (:) :: pv
real :: X1
real :: X2
real :: RMS
real :: MW
real :: SIG
real :: LAM
real, ALLOCATABLE :: CUA(:,:,:)
real, ALLOCATABLE :: CVA(:,:,:)
real, ALLOCATABLE, DIMENSION (:,:) :: P
real, ALLOCATABLE, DIMENSION (:,:) :: PP
real, ALLOCATABLE, DIMENSION (:,:) :: P2
real, ALLOCATABLE, DIMENSION (:,:) :: XMN
real, ALLOCATABLE, DIMENSION (:,:) :: HILFUV
real, ALLOCATABLE, DIMENSION (:) :: LNPMN
real, ALLOCATABLE, DIMENSION (:) :: LNPMN2
real, ALLOCATABLE, DIMENSION (:) :: LNPMN3
real, ALLOCATABLE, DIMENSION (:) :: WEIGHT
real, ALLOCATABLE, DIMENSION (:,:) :: UGVG
real, ALLOCATABLE, DIMENSION (:,:) :: DG
real, ALLOCATABLE, DIMENSION (:,:) :: ETAG
real, ALLOCATABLE, DIMENSION (:,:) :: GWSAVE
real, ALLOCATABLE, DIMENSION (:) :: PSG
real, ALLOCATABLE, DIMENSION (:) :: HILF
integer, ALLOCATABLE, DIMENSION (:) :: MLAT
integer, ALLOCATABLE, DIMENSION (:) :: MPSURF
integer, ALLOCATABLE, DIMENSION (:) :: MPFLUX
integer, ALLOCATABLE, DIMENSION (:) :: MPORO
integer, ALLOCATABLE, DIMENSION (:) :: MPAR
integer, ALLOCATABLE :: GIFAX(:,:)
real :: PI
real :: COSB
real :: DAK
real :: DBK
real :: P00
real :: URLAR8
real :: JMIN1
real :: LLLAR8
real :: MAXBMIN1
real :: PIR8
real :: DCOSB
integer :: I
integer :: J
integer :: K
integer :: L
integer :: IERR
integer :: M
integer :: LTEST
integer :: MK
integer :: NGI
integer :: NGJ
integer :: MFLUX
integer :: MSURF
integer :: MORO
integer :: LUNIT
integer :: LUNIT2
integer :: MAXL
integer :: MAXB
integer :: MLEVEL
integer :: LEVOUT
integer :: LEVMIN
integer :: LEVMAX
integer :: MOMEGA
integer :: MOMEGADIFF
integer :: MGAUSS
integer :: MSMOOTH
integer :: MNAUF
integer :: META
integer :: METADIFF
integer :: MDPDETA
integer :: METAPAR
real :: RLO0
real :: RLO1
real :: RLA0
real :: RLA1
character(len=300) :: MLEVELIST
integer :: MAUF
integer :: MANF
integer :: IFAX(10)
integer :: IGRIB(1)
integer :: iret
integer :: ogrib
character(len=80) :: FILENAME
Call graph
preconvert calls readspectral, phgcut, grph213, grib_close_file, statis, phgr213, gauleg, grib_open_file, set99, posnam, readlatlon, phgrad
readspectral calls grib_close_file, grib_count_in_file
phgcut calls phsymcut, phgpns
grph213 calls grphsub, ind
phgr213 calls phsym
gauleg calls dcos
readlatlon calls grib_close_file, grib_count_in_file
phgrad calls integermlat
phsymcut calls rfourtr
phgpns calls rfourtr
rfourtr calls fft99